database:
  image: mysql:5.6
  environment:
   - MYSQL_ROOT_PASSWORD=dbpw
   - MYSQL_DATABASE=guestbook

backend:
  build: backend
  links:
   - database:db
  environment:
   - DATASOURCE_PASSWORD=dbpw

frontend:
  build: frontend
  ports:
   - "80:80"
  links:
   - backend:backend